# ************************************************************分割线************************************************************

server:
  port: 80

sa-token:
  token-name: satoken
  timeout: 2592000 # 有效期，-1代表永久有效
  active-timeout: -1 # 最低活跃频率，-1代表永不冻结
  is-concurrent: true # 是否允许同一账号多地同时登录
  is-share: true # 在多人登录同一账号时，是否共用一个token
  token-style: uuid # token风格
  is-log: true
  jwt-secret-key: abcdefghijklmnopqrstuvwxyz # JWT秘钥

spring:
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    #    password:
    timeout: 10s

# 搭配RedissonConfig使用
redisson:
  threads: 8 # 线程池数量
  nettyThreads: 32 # Netty线程池数量
  singleServerConfig:
    clientName: test # 客户端名称
    connectionMinimumIdleSize: 8 # 最小空闲连接数
    connectionPoolSize: 32 # 连接池大小
    idleConnectionTimeout: 10000 # 连接空闲超时（毫秒）
    timeout: 3000 # 命令等待超时
    retryAttempts: 3 # 如果尝试在此限制之内发送成功，则开始启用timeout计时
    retryInterval: 1500 # 命令重试发送时间间隔
    subscriptionConnectionPoolSize: 50 # 发布和订阅连接池大小
